---
title: "Additional data visualisations"
output: html_document
date: "2026-04-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
library(pheatmap)
library(ggplot2)
```

Load data:

```{r load-data}

data = read.csv('../data/data_up_to_LoA.csv')
data.cc = data[complete.cases(data$NSAA_tot),]
```

Spaghetti plot:

```{r spaghetti}

data.cc |>
  ggplot(aes(x=age, y=NSAA_tot, group=Patient_ID, colour=factor(Patient_ID))) +
  geom_line() +
  geom_point(size=0.8) +
  labs(
    title='NSAA total score vs patient age at visit'
    , x='Age (years)'
    , y='NSAA'
  ) +
  theme(legend.position='none')
```

Heatmap:

```{r heatmap}

df.proteins = read.csv('../data/final_proteins.csv')

mat.proteins = subset(data.cc, select=df.proteins$x)
mat.proteins.scaled = t(scale(mat.proteins))

col.annotation = data.frame(
  NSAA_tot    = data.cc$NSAA_tot
  , Ambulation = ifelse(data.cc$NSAA_tot == 0, 'Non-ambulant', 'Ambulant')
)
rownames(col.annotation) = colnames(mat.proteins.scaled)

# png(filename = '../plots/heatmap_seven_proteins.png', res=150, width=1200, height=900)
pheatmap(
  mat.proteins.scaled,
  breaks=seq(-3,3, length.out=101),
  annotation_col=col.annotation,
  clustering_distance_cols = 'correlation',
  clustering_distance_rows = 'correlation',
  clustering_method='ward.D2',
  show_colnames= FALSE  # patient-time labels get crowded
)
# dev.off()
```